version : "2.24.7"

services:
  frontendimg :
    build : /root/Doc_Three_Tier/Frontend
    container_name: frontend
    ports:
    - "80:80"
    networks:
    - bridge

  backendimg :
   build : /root/Doc_Three_Tier/Backend
   container_name: backend
   ports:
   - "8080:8080"
   networks:
   - bridge
   depends_on: 
   - "frontendimg"